const datos = [
  {
      nombre: 'SERVICIO DE MANTENIMIENTO INTEGRAL Y RESIEMBRA DE CÉSPED DEL CAMPO DE GOLF JUAN BAUTISTA SEGURA',
      num_proceso: "1111-0442-LPU21",
      expediente: "EX-2021-10378435- -GCABA-DGTALAVJG",
      area: "SEC. DEPORTES",
      subarea: "FUTBOL dePORTIVO",
      firmante: "",
      modalidad: "SIN MODALIDAD",
      tipo_contrato: "LICITACION PUBLICA",
      estado: "Ejecucion",
      plazo: "32 meses",
      inicio: "2021-05-29T00:00:00.000+00:00",
      vencimiento: "2021-05-29T00:00:00.000+00:00",
      monto: 29641104.0,
      pliego_ingreso: null,
      pliego_egreso: null,
      salida_pg1: null,
      vuelta_pg1: null,
      fecha_llamado: "2021-12-04T00:00:00.000+00:00",
      apertura_ofertas: "2021-12-04T00:00:00.000+00:00",
      fecha_vencimiento_plazo_impugnacion: null,
      fecha_vencimiento_doc: null,
      salida_pg2: null,
      vuelta_pg2: null,
      fecha_aprobatoria: null,
      aprobatoria: "",
      renglon: [
        {
          _id: "65465438",
          descripcion: "Predio Este",
          monto: 29641104.0,
          oferta: [
            {
              _id: "1234",
              monto_ofertado: 1000000,
              observacion: "Muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Carlos SRL",
                  cuit: "23-45452214-2",
                },
              ],
            },
            {
              _id: "1235",
              monto_ofertado: 1100000,
              observacion: "Muy muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Miguel SRL",
                  cuit: "33-55484511-8",
                },
                {
                  razon_social: "Nakamura Contrstucciones SA",
                  cuit: "33-55541255-4",
                },
              ],
            },
          ],
        },
        {
          _id: "65465439",
          descripcion: "Predio Oeste",
          monto: 29641104.0,
          oferta: [
            {
              _id: "1244",
              monto_ofertado: 1000000,
              observacion: "Muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Carlos SRL",
                  cuit: "23-45452214-2",
                },
              ],
            },
            {
              _id: "1245",
              monto_ofertado: 1100000,
              observacion: "Muy muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Miguel SRL",
                  cuit: "33-55484511-8",
                },
                {
                  razon_social: "Nakamura Contrstucciones SA",
                  cuit: "33-55541255-4",
                },
              ],
            },
          ],
        },
      ],
      orden_compra: [
        {
          num_orden: "",
          monto: 0,
          tipo: "",
          prorroga: [
              {
              acta: "p2154112",
              vencimiento: "2024-04-20T00:00:00.000+00:00",
              }
          ],
          ampliatoria: [
              {
              acta: "N2154112",
              fecha: "2024-04-20T00:00:00.000+00:00",
              monto: 1000
              }
          ],
          destinatario: null,
          origen:"",
          ampliatoria_origen: "",
          prorroga_origen: "",
          renglon_origen: "",
          orden_compra: [],
          extension: [],
          control: [
              {
              num_certificado: "1",
              periodo: null,
              SPR: "",
              PRD: "",
              monto_ejecutado: 1000,
              monto_pagado:"",
              estado: "EJECUTADO",
              },
              {
              num_certificado: "2",
              periodo: null,
              SPR: "",
              PRD: "",
              monto_ejecutado: 1000,
              monto_pagado:"",
              estado: "EJECUTADO",
              },
              {
              num_certificado: "3",
              periodo: null,
              SPR: "",
              PRD: "",
              monto_ejecutado: "",
              monto_pagado:"",
              estado: "NO EJECUTADO",
              },
          ],
        },
        {
          num_orden: "353-9605-OC23",
          monto: "",
          tipo: "",
          
          prorroga: [],
          ampliatoria: [],
          destinatario: null,
          origen:"",
          ampliatoria_origen: "",
          prorroga_origen: "",
          renglon_origen: "",
          extension: [],
          control: [
            {
              num_certificado: "1",
              periodo: "2024-04-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "EJECUTADO",
            },
            {
              num_certificado: "2",
              periodo: "2024-05-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "EJECUTADO",
            },
            {
              num_certificado: "3",
              periodo: "2024-06-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "EJECUTADO",
            },
            {
              num_certificado: "4",
              periodo: "2024-07-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "EJECUTADO",
            },
            {
              num_certificado: "5",
              periodo: "2024-08-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "NO EJECUTADO",
            },
            {
              num_certificado: "6",
              periodo: "2024-09-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "NO EJECUTADO",
            },
            {
              num_certificado: "7",
              periodo: "2024-10-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "NO EJECUTADO",
            },
            {
              num_certificado: "8",
              periodo: "2024-11-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:"",
              estado: "NO EJECUTADO",
            },
          ],
        }
      ],
    },
    {
      nombre: 'RESIEMBRA DE CÉSPED DEL CAMPO DE GOLF JUAN BAUTISTA SEGURA',
      num_proceso: "1111-0442-LPU21",
      expediente: "EX-2021-10378435- -GCABA-DGTALAVJG",
      area: "SEC. DEPORTES",
      subarea: "FUTBOL INFANTIL",
      firmante: "FAA EL DIEGOO!",
      modalidad: "SIN MODALIDAD",
      tipo_contrato: "LICITACION PUBLICA",
      estado: "Ejecucion",
      plazo: "32 meses",
      inicio: "2021-05-29T00:00:00.000+00:00",
      vencimiento: "2021-05-29T00:00:00.000+00:00",
      monto: 29641104.0,
      pliego_ingreso: "2021-12-05T00:00:00.000+00:00",
      pliego_egreso: "2021-12-14T00:00:00.000+00:00",
      salida_pg1: "2021-12-24T00:00:00.000+00:00",
      vuelta_pg1: "2021-12-25T00:00:00.000+00:00",
      fecha_llamado: "2021-12-04T00:00:00.000+00:00",
      apertura_ofertas: "2021-12-04T00:00:00.000+00:00",
      fecha_vencimiento_plazo_impugnacion: "2021-12-30T00:00:00.000+00:00",
      fecha_vencimiento_doc: "2021-12-31T04:00:00.000+00:00",
      salida_pg2: "2022-01-01T00:00:00.000+00:00",
      vuelta_pg2: "2022-01-02T00:00:00.000+00:00",
      fecha_aprobatoria: "2022-01-05T00:00:00.000+00:00",
      aprobatoria: "EX-RYSMG-2022-00000001-GCABA-DGTALAVJG",
      renglon: [
        {
          _id: "65465438",
          descripcion: "Predio Este",
          monto: 29641104.0,
          oferta: [
            {
              _id: "1234",
              monto_ofertado: 1000000,
              observacion: "Muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Carlos SRL",
                  cuit: "23-45452214-2",
                },
              ],
            },
            {
              _id: "1235",
              monto_ofertado: 1100000,
              observacion: "Muy muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Miguel SRL",
                  cuit: "33-55484511-8",
                },
                {
                  razon_social: "Nakamura Contrstucciones SA",
                  cuit: "33-55541255-4",
                },
              ],
            },
          ],
        },
        {
          _id: "65465439",
          descripcion: "Predio Oeste",
          monto: 29641104.0,
          oferta: [
            {
              _id: "1244",
              monto_ofertado: 1000000,
              observacion: "Muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Carlos SRL",
                  cuit: "23-45452214-2",
                },
                {
                  razon_social: "Miguel SRL",
                  cuit: "23-45452214-2",
                },
              ],
            },
            {
              _id: "1245",
              monto_ofertado: 1100000,
              observacion: "Muy muy caro",
              ganador: false,
              documentacion: true,
              beneficiario: [
                {
                  razon_social: "Miguel SRL",
                  cuit: "33-55484511-8",
                },
                {
                  razon_social: "Nakamura Contrstucciones SA",
                  cuit: "33-55541255-4",
                },
              ],
            },
          ],
        },
      ],
      orden_compra: [
        {
          num_orden: "353-9605-OC23",
          monto: 10525411,
          tipo: "CERRADA",
          prorroga: [
              {
              acta: "p2154112",
              vencimiento: "2024-04-20T00:00:00.000+00:00",
              }
          ],
          ampliatoria: [
              {
              acta: "N2154112",
              fecha: "2024-04-20T00:00:00.000+00:00",
              monto: 1000
              }
          ],
          destinatario: [
            {
              razon_social: "Carlos SRL",
              cuit: "23-45452214-2",
            },
            {
              razon_social: "Miguel SRL",
              cuit: "23-45452214-2",
            },
          ],
          origen:"AMPLIATORIA",
          ampliatoria_origen: "N2154112",
          prorroga_origen: "",
          renglon_origen: "",
          orden_compra: [],
          extension: [],
          control: [
              {
              num_certificado: "1",
              periodo: null,
              SPR: "",
              PRD: "",
              monto_ejecutado: 1000,
              monto_pagado:"",
              estado: "EJECUTADO",
              },
              {
              num_certificado: "2",
              periodo: null,
              SPR: "",
              PRD: "",
              monto_ejecutado: 1000,
              monto_pagado:"",
              estado: "EJECUTADO",
              },
              {
              num_certificado: "3",
              periodo: null,
              SPR: "",
              PRD: "",
              monto_ejecutado: "",
              monto_pagado:"",
              estado: "NO EJECUTADO",
              },
          ],
        },
        {
          num_orden: "353-9605-OC23",
          monto: 10000,
          tipo: "",
          
          prorroga: [],
          ampliatoria: [],
          destinatario: [],
          origen:"",
          ampliatoria_origen: "",
          prorroga_origen: "",
          renglon_origen: "",
          extension: [],
          control: [
            {
              num_certificado: "1",
              periodo: "2024-04-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "EJECUTADO",
            },
            {
              num_certificado: "2",
              periodo: "2024-05-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "EJECUTADO",
            },
            {
              num_certificado: "3",
              periodo: "2024-06-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "EJECUTADO",
            },
            {
              num_certificado: "4",
              periodo: "2024-07-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "EJECUTADO",
            },
            {
              num_certificado: "5",
              periodo: "2024-08-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "NO EJECUTADO",
            },
            {
              num_certificado: "6",
              periodo: "2024-09-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "NO EJECUTADO",
            },
            {
              num_certificado: "7",
              periodo: "2024-10-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "NO EJECUTADO",
            },
            {
              num_certificado: "8",
              periodo: "2024-11-20T00:00:00.000+00:00",
              SPR: "No aplica",
              PRD: "227878-23",
              monto_ejecutado: 2470092,
              monto_pagado:0,
              estado: "NO EJECUTADO",
            },
          ],
        }
      ],
    },
]

const empyData = {
  nombre: '',
  num_proceso: "",
  expediente: "",
  area: "",
  subarea: "",
  firmante: "",
  modalidad: "",
  tipo_contrato: "",
  estado: "",
  plazo: "",
  inicio: "",
  vencimiento: "",
  monto: "",
  pliego_ingreso: null,
  pliego_egreso: null,
  salida_pg1: null,
  vuelta_pg1: null,
  fecha_llamado: null,
  apertura_ofertas: null,
  fecha_vencimiento_plazo_impugnacion: null,
  fecha_vencimiento_doc: null,
  salida_pg2: null,
  vuelta_pg2: null,
  fecha_aprobatoria: null,
  aprobatoria: "",
  renglon: [
    {
      _id: "65465438",
      descripcion: "Predio Este",
      monto: 0,
      oferta: [
        {
          _id: "1234",
          monto_ofertado: 1000000,
          observacion: "Muy caro",
          ganador: false,
          documentacion: true,
          beneficiario: [
            {
              razon_social: "Carlos SRL",
              cuit: "23-45452214-2",
            },
          ],
        },
        {
          _id: "1235",
          monto_ofertado: 1100000,
          observacion: "Muy muy caro",
          ganador: false,
          documentacion: true,
          beneficiario: [
            {
              razon_social: "Miguel SRL",
              cuit: "33-55484511-8",
            },
            {
              razon_social: "Nakamura Contrstucciones SA",
              cuit: "33-55541255-4",
            },
          ],
        },
      ],
    },
  ],
  orden_compra: [{
    num_orden: "",
    monto: 0,
    tipo: "",
    prorroga: [
      {
        acta: "p2154112",
        vencimiento: "2024-04-20T00:00:00.000+00:00",
      }
    ],
    ampliatoria: [
      {
        acta: "N2154112",
        fecha: "2024-04-20T00:00:00.000+00:00",
        monto: 1000
      }
    ],
    destinatario: null,
    origen:"",
    ampliatoria_origen: "",
    prorroga_origen: "",
    renglon_origen: "",
    orden_compra: [],
    extension: [],
    control: [
      {
        num_certificado: "1",
        periodo: null,
        SPR: "",
        PRD: "",
        monto_ejecutado: 1000,
        monto_pagado:"",
        estado: "EJECUTADO",
      },
      {
        num_certificado: "2",
        periodo: null,
        SPR: "",
        PRD: "",
        monto_ejecutado: 1000,
        monto_pagado:"",
        estado: "EJECUTADO",
      },
      {
        num_certificado: "3",
        periodo: null,
        SPR: "",
        PRD: "",
        monto_ejecutado: "",
        monto_pagado:"",
        estado: "NO EJECUTADO",
      },
    ],
  }],
}

const data = { datos, empyData }

export default data;